export const DtsFilename = 'cloudflare.d.ts';

export function getDefaultTsconfig() {
  const tsconfig = {
    compilerOptions: {
      jsx: 'preserve',
      target: 'ESNext',
      module: 'ESNext',
      moduleResolution: 'Node',
      skipLibCheck: true,
      strict: false,
      allowJs: true,
      noEmit: true,
      resolveJsonModule: true,
      allowSyntheticDefaultImports: true,
      baseUrl: '..',
      paths: {}
    },
    include: ['./' + DtsFilename, '../**/*']
  };
  return '// Generated by vite-plugin-cloudflare-functions\n' + JSON.stringify(tsconfig, null, 2);
}

export function getDts() {
  return [`/// <reference types="@cloudflare/workers-types" />`].join('\n');
}
